version: '3.8'

services:
  blog-server:
    build: .
    extra_hosts:
      - 'host.docker.internal:host-gateway' # 服务器上需使用 host.docker.internal
    ports:
      - '8888:8888'
      - '8889:8889'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=Asia/Shanghai
    networks:
      - blog-network

  db:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=online_blog
      - TZ=Asia/Shanghai
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=12345678"]
      interval: 10s
      retries: 5
    networks:
      - blog-network

  netease-music-api:
    image: binaryify/netease_cloud_music_api:latest
    ports:
      - '3000:3000'
    networks:
      - blog-network

  nginx:
    image: nginx:alpine
    restart: always
    command: nginx -g "daemon off;"
    ports:
      - '80:80'
    volumes:
      - ./ui/admin/dist:/usr/share/nginx/html/admin  # 挂载前端静态文件
      - ./ui/blog/dist:/usr/share/nginx/html/blog
      - ./nginx.conf:/etc/nginx/nginx.conf       # 挂载 Nginx 配置文件
    depends_on:
      - blog-server
    networks:
      - blog-network

  minio:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9999"
    ports:
      - "9000:9000"  # API port
      - "9999:9999"  # Console port
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=123456
    volumes:
      - ./minio/data:/data
    networks:
      - blog-network

volumes:
  db_data:

networks:
  blog-network:
    driver: bridge